/* XRZENO body copy — single source of truth for both language builds.
   Production: bake `/` from `id` and `/en/` from `en` (static, SEO-bearing).
   Preview/drawer toggle: runtime swap via data-i18n keys.
   ⚠ `id` strings are machine-drafted — native review before launch. */
window.XR_STRINGS = {
  en: {
    "drawer.portfolio": "Portfolio",
    "drawer.benefits": "Benefits",
    "drawer.process": "How it works",
    "drawer.faq": "FAQ",
    "drawer.contact": "Contact",
    "drawer.about": "About",
    "drawer.whatsapp": "Chat on WhatsApp",
    "drawer.lang": "Bahasa Indonesia",
    "about.p1": "XRZENO is a WebAR product-visualization studio in Tangerang Selatan, Banten. We started in early 2026 because no one should have to guess what a product looks like from a flat photo.",
    "about.p2": "So we scan real products and rebuild them as accurate 3D models your customers can turn over, and place in their own space at true size, straight from the browser. No app to install.",
    "about.p3": "We build for everyone, from a single shop to a full catalog, and we keep the process quick and the pricing clear.",

    "compare.eyebrow": "Real vs Render",
    "compare.title": "One of these is a photograph.",
    "compare.body": "Every model we deliver starts as the physical product on our scanner. Drag the divider. The left side is the photo, the right side is our 3D render. This is the accuracy your customers will hold in their hands.",
    "compare.labelReal": "Photo",
    "compare.labelRender": "Render",

    "portfolio.eyebrow": "Portfolio",
    "portfolio.title": "Built from real products.",
    "portfolio.body": "Explore the possibilities. View on your phone for the full AR experience.",
    "portfolio.ar": "View in your space",

    "benefits.eyebrow": "The payoff",
    "benefits.title": "People buy what they can see.",
    "benefits.item1.title": "They trade up",
    "benefits.item1.body": "Let a customer turn your product over at real size and the pricier option stops feeling like a gamble. They reach for it because they already know what they're getting.",
    "benefits.item2.title": "No surprises",
    "benefits.item2.body": "A customer who has set your product on their own table knows exactly what will arrive. The expectation is set before the sale, so far fewer products get returned.",
    "benefits.item3.title": "It spreads",
    "benefits.item3.body": "AR is the kind of thing people record and send to a friend. Every share puts your product in front of someone new. Effectively free marketing at no extra cost.",

    "howwework.title": "All we need from you is the product.",
    "howwework.step1.title": "Discuss",
    "howwework.step1.body": "We pick the products with the most to gain from 3D: the ones people want to turn over before they commit. You point them out, we plan the shoot.",
    "howwework.step2.title": "Scan",
    "howwework.step2.body": "Our team captures the real product in detail, at our studio or on your site.",
    "howwework.step3.title": "Build",
    "howwework.step3.body": "That capture becomes a clean, accurate 3D model, tuned to load fast on any phone.",
    "howwework.step4.title": "Deliver",
    "howwework.step4.body": "You get a link and a QR code, ready for a shelf, a table, or your website. Customers point their camera and it's there.",

    "process.eyebrow": "How it works",

    "faq.eyebrow": "FAQ",
    "faq.title": "Common questions",
    "faq.q1": "Do my customers need to install an app?",
    "faq.a1": "No. Everything runs in the phone's browser and native AR viewer. They scan a QR code or tap a link. That's it.",
    "faq.q2": "Which devices are supported?",
    "faq.a2": "iPhone and iPad (iOS 12+) and the vast majority of Android phones support the AR view. Every device with a browser can use the 3D viewer.",
    "faq.q3": "What do you need from us to start?",
    "faq.a3": "Just the physical product. We handle photography, scanning, and rebuilding. If you have brand assets (logos, label artwork), they help us polish the result.",
    "faq.q4": "How long does it take?",
    "faq.a4": "Usually 5–10 working days per product. Larger catalogs are scanned in batches with a schedule we agree upfront.",
    "faq.q5": "Is the size in AR accurate?",
    "faq.a5": "Yes. Models are placed at true 1:1 scale. A 750ml bottle on your customer's table is exactly as tall as the real one.",
    "faq.q6": "How much does it cost?",
    "faq.a6": "Pricing depends on product complexity and catalog size. Message us on WhatsApp with what you sell and we'll quote within a day.",

    "cta.title": "Show your product, not a picture of it.",
    "cta.body": "Tell us what you make. We'll answer within a day.",
    "cta.whatsapp": "Chat on WhatsApp",
    "cta.email": "Email us",
    "cta.waPrefill": "Hi XRZENO, I'd like to talk about 3D/AR visualization for my product.",

    "footer.tagline": "WebAR & product visualization",
    "footer.studioLabel": "Studio",
    "footer.location": "Tangerang Selatan, Banten, Indonesia",
    "footer.hours": "Mon–Fri, 9am–6pm",
    "footer.contactLabel": "Contact",
    "footer.wa": "WhatsApp",
    "footer.privacy": "Privacy",
    "footer.rights": "© 2026 XRZENO. All rights reserved."
  },

  id: {
    "drawer.portfolio": "Portofolio",
    "drawer.benefits": "Keuntungan",
    "drawer.process": "Cara kerja",
    "drawer.faq": "FAQ",
    "drawer.contact": "Kontak",
    "drawer.about": "Tentang",
    "drawer.whatsapp": "Chat via WhatsApp",
    "drawer.lang": "English",
    "about.p1": "XRZENO adalah studio visualisasi produk WebAR di Tangerang Selatan, Banten. Kami mulai di awal 2026 karena tidak seharusnya orang menebak wujud produk hanya dari foto.",
    "about.p2": "Maka kami memindai produk asli dan membangunnya kembali menjadi model 3D akurat yang bisa diputar pelanggan, dan ditempatkan di ruang mereka sendiri dengan ukuran nyata, langsung dari browser. Tanpa perlu aplikasi.",
    "about.p3": "Kami membangun untuk semua skala, dari satu toko hingga katalog besar, dengan proses yang cepat dan harga yang transparan.",

    "compare.eyebrow": "Asli vs Render",
    "compare.title": "Salah satunya adalah foto.",
    "compare.body": "Setiap model yang kami buat dimulai dari produk fisik di scanner kami. Geser pembatasnya. Sisi kiri foto asli, sisi kanan render 3D kami. Inilah tingkat akurasi yang akan dilihat pelanggan Anda.",
    "compare.labelReal": "Foto",
    "compare.labelRender": "Render",

    "portfolio.eyebrow": "Portofolio",
    "portfolio.title": "Dibuat dari produk asli.",
    "portfolio.body": "Jelajahi kemungkinannya. Buka di ponsel untuk pengalaman AR sepenuhnya.",
    "portfolio.ar": "Lihat di ruangan Anda",

    "benefits.eyebrow": "Hasilnya",
    "benefits.title": "Orang membeli apa yang bisa mereka lihat.",
    "benefits.item1.title": "Mereka pilih yang lebih premium",
    "benefits.item1.body": "Saat pelanggan bisa memutar produk Anda dalam ukuran asli, opsi yang lebih mahal tak lagi terasa berisiko. Mereka memilihnya karena sudah tahu persis apa yang akan didapat.",
    "benefits.item2.title": "Tanpa kejutan",
    "benefits.item2.body": "Pelanggan yang sudah menaruh produk Anda di meja sendiri tahu persis apa yang akan datang. Ekspektasi terbentuk sebelum membeli, jadi jauh lebih sedikit yang kembali setelahnya.",
    "benefits.item3.title": "Menyebar sendiri",
    "benefits.item3.body": "AR adalah hal yang direkam pelanggan lalu dikirim ke teman. Setiap kali dibagikan, produk Anda tampil ke orang baru. Praktis jadi promosi gratis tanpa biaya tambahan.",

    "howwework.title": "Yang kami butuhkan dari Anda hanya produknya.",
    "howwework.step1.title": "Diskusi",
    "howwework.step1.body": "Kami pilih produk yang paling diuntungkan dengan tampilan 3D: yang ingin dilihat pelanggan dari dekat sebelum membeli. Anda tunjukkan, kami rencanakan pemotretannya.",
    "howwework.step2.title": "Scan",
    "howwework.step2.body": "Tim kami mengambil detail produk asli Anda, di studio kami atau di lokasi Anda.",
    "howwework.step3.title": "Produksi 3D",
    "howwework.step3.body": "Hasil pemotretan itu kami bangun jadi model 3D yang rapi dan akurat, dioptimalkan agar cepat dibuka di ponsel apa pun.",
    "howwework.step4.title": "Siap Digunakan",
    "howwework.step4.body": "Anda menerima link dan kode QR, siap untuk rak, meja, atau situs web Anda. Pelanggan cukup arahkan kamera, dan produk langsung muncul.",

    "process.eyebrow": "Cara kerja",

    "faq.eyebrow": "FAQ",
    "faq.title": "Pertanyaan umum",
    "faq.q1": "Apakah pelanggan saya perlu install aplikasi?",
    "faq.a1": "Tidak. Semuanya berjalan di browser dan AR viewer bawaan ponsel. Cukup scan kode QR atau buka link.",
    "faq.q2": "Perangkat apa saja yang didukung?",
    "faq.a2": "iPhone dan iPad (iOS 12+) serta mayoritas ponsel Android mendukung tampilan AR. Semua perangkat dengan browser bisa memakai viewer 3D-nya.",
    "faq.q3": "Apa yang perlu kami siapkan untuk mulai?",
    "faq.a3": "Cukup produk fisiknya. Fotografi, scanning, dan rebuild kami yang kerjakan. Aset brand (logo, artwork label) membantu hasil akhir lebih rapi.",
    "faq.q4": "Berapa lama pengerjaannya?",
    "faq.a4": "Umumnya 5–10 hari kerja per produk. Katalog besar dipindai bertahap dengan jadwal yang disepakati di awal.",
    "faq.q5": "Apakah ukuran di AR akurat?",
    "faq.a5": "Ya, model ditempatkan dengan skala 1:1. Botol 750ml di meja pelanggan Anda tingginya persis seperti aslinya.",
    "faq.q6": "Berapa biayanya?",
    "faq.a6": "Harga tergantung kompleksitas produk dan ukuran katalog. Kirim pesan WhatsApp tentang produk Anda, kami kirim penawaran dalam sehari.",

    "cta.title": "Tunjukkan produknya, bukan sekadar fotonya.",
    "cta.body": "Ceritakan apa yang Anda jual. Kami balas dalam sehari.",
    "cta.whatsapp": "Chat via WhatsApp",
    "cta.email": "Email kami",
    "cta.waPrefill": "Halo XRZENO, saya ingin diskusi visualisasi 3D/AR untuk produk saya.",

    "footer.tagline": "WebAR & visualisasi produk",
    "footer.studioLabel": "Studio",
    "footer.location": "Tangerang Selatan, Banten, Indonesia",
    "footer.hours": "Sen–Jum, 09.00–18.00",
    "footer.contactLabel": "Kontak",
    "footer.wa": "WhatsApp",
    "footer.privacy": "Privasi",
    "footer.rights": "© 2026 XRZENO. Hak cipta dilindungi."
  }
};
